-- =============================================================================
-- Migration: Create idempotency_record table
-- =============================================================================
-- This table stores idempotency records for all mutation endpoints.
-- The unique constraint on (userId, key) is the cornerstone:
--   • It prevents duplicate rows at the DB level (concurrent safe).
--   • Combined with PROCESSING status detection it prevents race conditions.
--
-- Expiry policy: records older than expiresAt are treated as expired.
--   A scheduled job / cron should DELETE WHERE expiresAt < NOW() periodically.
-- =============================================================================

CREATE TYPE idempotency_status_enum AS ENUM ('PROCESSING', 'COMPLETED', 'FAILED');

CREATE TABLE IF NOT EXISTS "idempotency_record" (
  "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- The account that owns this idempotency record
  "userId"          INT           NOT NULL,

  -- The client-generated UUID key
  "key"             VARCHAR(64)   NOT NULL,

  -- METHOD:path fingerprint (e.g. "POST:/financial-transaction/create")
  "endpoint"        VARCHAR(255)  NOT NULL,

  -- SHA-256 hash of the serialised request body (detects body mismatches)
  "bodyHash"        VARCHAR(64)   NOT NULL,

  -- Current lifecycle status
  "status"          idempotency_status_enum NOT NULL DEFAULT 'PROCESSING',

  -- HTTP status code of the stored response (NULL while PROCESSING)
  "responseStatus"  INT           NULL,

  -- Serialised JSON response body (NULL while PROCESSING)
  "responseBody"    JSONB         NULL,

  -- Auto-expiry: after this timestamp the record is considered stale
  "expiresAt"       TIMESTAMPTZ   NOT NULL DEFAULT NOW() + INTERVAL '24 hours',

  "createdAt"       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  "updatedAt"       TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────────────────────
-- Unique constraint: same user cannot use the same key twice (unless expired)
-- ──────────────────────────────────────────────────────────────────────────────
ALTER TABLE "idempotency_record"
  ADD CONSTRAINT "UQ_idempotency_user_key" UNIQUE ("userId", "key");

-- Index for looking up a single record by userId + key (covered by UQ above)
CREATE INDEX IF NOT EXISTS "IDX_idempotency_user_key"
  ON "idempotency_record" ("userId", "key");

-- Index for expiry cleanup jobs
CREATE INDEX IF NOT EXISTS "IDX_idempotency_expires_at"
  ON "idempotency_record" ("expiresAt");

-- ──────────────────────────────────────────────────────────────────────────────
-- Cleanup: delete expired records automatically (requires pg_cron extension).
-- If pg_cron is not available, run this periodically from your application or
-- a scheduled job.
-- ──────────────────────────────────────────────────────────────────────────────
-- SELECT cron.schedule('cleanup-idempotency', '0 * * * *',
--   $$DELETE FROM "idempotency_record" WHERE "expiresAt" < NOW()$$);
