import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Migration: Create idempotency_record table.
 *
 * Run with: npx typeorm migration:run
 * Revert with: npx typeorm migration:revert
 */
export class CreateIdempotencyRecord1728439200000 implements MigrationInterface {
  name = "CreateIdempotencyRecord1728439200000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Create ENUM type for status
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "idempotency_status_enum" AS ENUM ('PROCESSING', 'COMPLETED', 'FAILED');
      EXCEPTION
        WHEN duplicate_object THEN null;
      END $$;
    `);

    // Create the table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "idempotency_record" (
        "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "userId"          INT           NOT NULL,
        "key"             VARCHAR(64)   NOT NULL,
        "endpoint"        VARCHAR(255)  NOT NULL,
        "bodyHash"        VARCHAR(64)   NOT NULL,
        "status"          "idempotency_status_enum" NOT NULL DEFAULT 'PROCESSING',
        "responseStatus"  INT           NULL,
        "responseBody"    JSONB         NULL,
        "expiresAt"       TIMESTAMPTZ   NOT NULL DEFAULT NOW() + INTERVAL '24 hours',
        "createdAt"       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
        "updatedAt"       TIMESTAMPTZ   NOT NULL DEFAULT NOW()
      )
    `);

    // Unique constraint — the heart of idempotency safety
    await queryRunner.query(`
      ALTER TABLE "idempotency_record"
        ADD CONSTRAINT "UQ_idempotency_user_key" UNIQUE ("userId", "key")
    `);

    // Performance index for expiry cleanup
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_idempotency_expires_at"
        ON "idempotency_record" ("expiresAt")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "idempotency_record"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "idempotency_status_enum"`);
  }
}
