export enum FINANCIAL_GOAL_TYPE {
  SAVING = "SAVING",
  INVESTMENT = "INVESTMENT",
  DEBT_PAYMENT = "DEBT_PAYMENT",
  EMERGENCY_FUND = "EMERGENCY_FUND",
  OTHER = "OTHER",
}

export enum FINANCIAL_GOAL_SAVING_MODE {
  MANUAL = "MANUAL",
  AUTO = "AUTO",
}

export enum FINANCIAL_GOAL_STATUS {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  INACTIVE = "INACTIVE",
}
