/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as R404RouteImport } from './../../routes/404'
import { Route as R401RouteImport } from './../../routes/401'
import { Route as publicRouteRouteImport } from './../../routes/(public)/route'
import { Route as protectedRouteRouteImport } from './../../routes/(protected)/route'
import { Route as IndexRouteImport } from './../../routes/index'
import { Route as publicLoginRouteImport } from './../../routes/(public)/login'
import { Route as publicIconRouteImport } from './../../routes/(public)/icon'
import { Route as publicDemoComponentRouteImport } from './../../routes/(public)/demoComponent'
import { Route as protectedUserRouteImport } from './../../routes/(protected)/user'
import { Route as protectedDashboardRouteImport } from './../../routes/(protected)/dashboard'
import { Route as protectedPhotoboothRouteRouteImport } from './../../routes/(protected)/photobooth/route'
import { Route as protectedOrderRouteRouteImport } from './../../routes/(protected)/order/route'
import { Route as protectedPhotoboothIndexRouteImport } from './../../routes/(protected)/photobooth/index'
import { Route as protectedProductListRouteRouteImport } from './../../routes/(protected)/product/list/route'
import { Route as protectedOrderListRouteRouteImport } from './../../routes/(protected)/order/list/route'
import { Route as protectedOrderListIndexRouteImport } from './../../routes/(protected)/order/list/index'
import { Route as protectedProductListSubListRouteRouteImport } from './../../routes/(protected)/product/list/$subList/route'
import { Route as protectedProductListSubListIndexRouteImport } from './../../routes/(protected)/product/list/$subList/index'
import { Route as protectedOrderListViewIdRouteImport } from './../../routes/(protected)/order/list/view.$id'
import { Route as protectedProductListSubListWriteIdRouteImport } from './../../routes/(protected)/product/list/$subList/write.$id'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicIconRoute = publicIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicDemoComponentRoute = publicDemoComponentRouteImport.update({
  id: '/demoComponent',
  path: '/demoComponent',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedUserRoute = protectedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedPhotoboothRouteRoute =
  protectedPhotoboothRouteRouteImport.update({
    id: '/photobooth',
    path: '/photobooth',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedOrderRouteRoute = protectedOrderRouteRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedPhotoboothIndexRoute =
  protectedPhotoboothIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedPhotoboothRouteRoute,
  } as any)
const protectedProductListRouteRoute =
  protectedProductListRouteRouteImport.update({
    id: '/product/list',
    path: '/product/list',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedOrderListRouteRoute = protectedOrderListRouteRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => protectedOrderRouteRoute,
} as any)
const protectedOrderListIndexRoute = protectedOrderListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedOrderListRouteRoute,
} as any)
const protectedProductListSubListRouteRoute =
  protectedProductListSubListRouteRouteImport.update({
    id: '/$subList',
    path: '/$subList',
    getParentRoute: () => protectedProductListRouteRoute,
  } as any)
const protectedProductListSubListIndexRoute =
  protectedProductListSubListIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedProductListSubListRouteRoute,
  } as any)
const protectedOrderListViewIdRoute =
  protectedOrderListViewIdRouteImport.update({
    id: '/view/$id',
    path: '/view/$id',
    getParentRoute: () => protectedOrderListRouteRoute,
  } as any)
const protectedProductListSubListWriteIdRoute =
  protectedProductListSubListWriteIdRouteImport.update({
    id: '/write/$id',
    path: '/write/$id',
    getParentRoute: () => protectedProductListSubListRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/order': typeof protectedOrderRouteRouteWithChildren
  '/photobooth': typeof protectedPhotoboothRouteRouteWithChildren
  '/dashboard': typeof protectedDashboardRoute
  '/user': typeof protectedUserRoute
  '/demoComponent': typeof publicDemoComponentRoute
  '/icon': typeof publicIconRoute
  '/login': typeof publicLoginRoute
  '/order/list': typeof protectedOrderListRouteRouteWithChildren
  '/product/list': typeof protectedProductListRouteRouteWithChildren
  '/photobooth/': typeof protectedPhotoboothIndexRoute
  '/product/list/$subList': typeof protectedProductListSubListRouteRouteWithChildren
  '/order/list/': typeof protectedOrderListIndexRoute
  '/order/list/view/$id': typeof protectedOrderListViewIdRoute
  '/product/list/$subList/': typeof protectedProductListSubListIndexRoute
  '/product/list/$subList/write/$id': typeof protectedProductListSubListWriteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/order': typeof protectedOrderRouteRouteWithChildren
  '/dashboard': typeof protectedDashboardRoute
  '/user': typeof protectedUserRoute
  '/demoComponent': typeof publicDemoComponentRoute
  '/icon': typeof publicIconRoute
  '/login': typeof publicLoginRoute
  '/product/list': typeof protectedProductListRouteRouteWithChildren
  '/photobooth': typeof protectedPhotoboothIndexRoute
  '/order/list': typeof protectedOrderListIndexRoute
  '/order/list/view/$id': typeof protectedOrderListViewIdRoute
  '/product/list/$subList': typeof protectedProductListSubListIndexRoute
  '/product/list/$subList/write/$id': typeof protectedProductListSubListWriteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/(protected)/order': typeof protectedOrderRouteRouteWithChildren
  '/(protected)/photobooth': typeof protectedPhotoboothRouteRouteWithChildren
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(protected)/user': typeof protectedUserRoute
  '/(public)/demoComponent': typeof publicDemoComponentRoute
  '/(public)/icon': typeof publicIconRoute
  '/(public)/login': typeof publicLoginRoute
  '/(protected)/order/list': typeof protectedOrderListRouteRouteWithChildren
  '/(protected)/product/list': typeof protectedProductListRouteRouteWithChildren
  '/(protected)/photobooth/': typeof protectedPhotoboothIndexRoute
  '/(protected)/product/list/$subList': typeof protectedProductListSubListRouteRouteWithChildren
  '/(protected)/order/list/': typeof protectedOrderListIndexRoute
  '/(protected)/order/list/view/$id': typeof protectedOrderListViewIdRoute
  '/(protected)/product/list/$subList/': typeof protectedProductListSubListIndexRoute
  '/(protected)/product/list/$subList/write/$id': typeof protectedProductListSubListWriteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/404'
    | '/order'
    | '/photobooth'
    | '/dashboard'
    | '/user'
    | '/demoComponent'
    | '/icon'
    | '/login'
    | '/order/list'
    | '/product/list'
    | '/photobooth/'
    | '/product/list/$subList'
    | '/order/list/'
    | '/order/list/view/$id'
    | '/product/list/$subList/'
    | '/product/list/$subList/write/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/404'
    | '/order'
    | '/dashboard'
    | '/user'
    | '/demoComponent'
    | '/icon'
    | '/login'
    | '/product/list'
    | '/photobooth'
    | '/order/list'
    | '/order/list/view/$id'
    | '/product/list/$subList'
    | '/product/list/$subList/write/$id'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(public)'
    | '/401'
    | '/404'
    | '/(protected)/order'
    | '/(protected)/photobooth'
    | '/(protected)/dashboard'
    | '/(protected)/user'
    | '/(public)/demoComponent'
    | '/(public)/icon'
    | '/(public)/login'
    | '/(protected)/order/list'
    | '/(protected)/product/list'
    | '/(protected)/photobooth/'
    | '/(protected)/product/list/$subList'
    | '/(protected)/order/list/'
    | '/(protected)/order/list/view/$id'
    | '/(protected)/product/list/$subList/'
    | '/(protected)/product/list/$subList/write/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  R401Route: typeof R401Route
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/icon': {
      id: '/(public)/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof publicIconRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/demoComponent': {
      id: '/(public)/demoComponent'
      path: '/demoComponent'
      fullPath: '/demoComponent'
      preLoaderRoute: typeof publicDemoComponentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/user': {
      id: '/(protected)/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof protectedUserRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/photobooth': {
      id: '/(protected)/photobooth'
      path: '/photobooth'
      fullPath: '/photobooth'
      preLoaderRoute: typeof protectedPhotoboothRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/order': {
      id: '/(protected)/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof protectedOrderRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/photobooth/': {
      id: '/(protected)/photobooth/'
      path: '/'
      fullPath: '/photobooth/'
      preLoaderRoute: typeof protectedPhotoboothIndexRouteImport
      parentRoute: typeof protectedPhotoboothRouteRoute
    }
    '/(protected)/product/list': {
      id: '/(protected)/product/list'
      path: '/product/list'
      fullPath: '/product/list'
      preLoaderRoute: typeof protectedProductListRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/order/list': {
      id: '/(protected)/order/list'
      path: '/list'
      fullPath: '/order/list'
      preLoaderRoute: typeof protectedOrderListRouteRouteImport
      parentRoute: typeof protectedOrderRouteRoute
    }
    '/(protected)/order/list/': {
      id: '/(protected)/order/list/'
      path: '/'
      fullPath: '/order/list/'
      preLoaderRoute: typeof protectedOrderListIndexRouteImport
      parentRoute: typeof protectedOrderListRouteRoute
    }
    '/(protected)/product/list/$subList': {
      id: '/(protected)/product/list/$subList'
      path: '/$subList'
      fullPath: '/product/list/$subList'
      preLoaderRoute: typeof protectedProductListSubListRouteRouteImport
      parentRoute: typeof protectedProductListRouteRoute
    }
    '/(protected)/product/list/$subList/': {
      id: '/(protected)/product/list/$subList/'
      path: '/'
      fullPath: '/product/list/$subList/'
      preLoaderRoute: typeof protectedProductListSubListIndexRouteImport
      parentRoute: typeof protectedProductListSubListRouteRoute
    }
    '/(protected)/order/list/view/$id': {
      id: '/(protected)/order/list/view/$id'
      path: '/view/$id'
      fullPath: '/order/list/view/$id'
      preLoaderRoute: typeof protectedOrderListViewIdRouteImport
      parentRoute: typeof protectedOrderListRouteRoute
    }
    '/(protected)/product/list/$subList/write/$id': {
      id: '/(protected)/product/list/$subList/write/$id'
      path: '/write/$id'
      fullPath: '/product/list/$subList/write/$id'
      preLoaderRoute: typeof protectedProductListSubListWriteIdRouteImport
      parentRoute: typeof protectedProductListSubListRouteRoute
    }
  }
}

interface protectedOrderListRouteRouteChildren {
  protectedOrderListIndexRoute: typeof protectedOrderListIndexRoute
  protectedOrderListViewIdRoute: typeof protectedOrderListViewIdRoute
}

const protectedOrderListRouteRouteChildren: protectedOrderListRouteRouteChildren =
  {
    protectedOrderListIndexRoute: protectedOrderListIndexRoute,
    protectedOrderListViewIdRoute: protectedOrderListViewIdRoute,
  }

const protectedOrderListRouteRouteWithChildren =
  protectedOrderListRouteRoute._addFileChildren(
    protectedOrderListRouteRouteChildren,
  )

interface protectedOrderRouteRouteChildren {
  protectedOrderListRouteRoute: typeof protectedOrderListRouteRouteWithChildren
}

const protectedOrderRouteRouteChildren: protectedOrderRouteRouteChildren = {
  protectedOrderListRouteRoute: protectedOrderListRouteRouteWithChildren,
}

const protectedOrderRouteRouteWithChildren =
  protectedOrderRouteRoute._addFileChildren(protectedOrderRouteRouteChildren)

interface protectedPhotoboothRouteRouteChildren {
  protectedPhotoboothIndexRoute: typeof protectedPhotoboothIndexRoute
}

const protectedPhotoboothRouteRouteChildren: protectedPhotoboothRouteRouteChildren =
  {
    protectedPhotoboothIndexRoute: protectedPhotoboothIndexRoute,
  }

const protectedPhotoboothRouteRouteWithChildren =
  protectedPhotoboothRouteRoute._addFileChildren(
    protectedPhotoboothRouteRouteChildren,
  )

interface protectedProductListSubListRouteRouteChildren {
  protectedProductListSubListIndexRoute: typeof protectedProductListSubListIndexRoute
  protectedProductListSubListWriteIdRoute: typeof protectedProductListSubListWriteIdRoute
}

const protectedProductListSubListRouteRouteChildren: protectedProductListSubListRouteRouteChildren =
  {
    protectedProductListSubListIndexRoute:
      protectedProductListSubListIndexRoute,
    protectedProductListSubListWriteIdRoute:
      protectedProductListSubListWriteIdRoute,
  }

const protectedProductListSubListRouteRouteWithChildren =
  protectedProductListSubListRouteRoute._addFileChildren(
    protectedProductListSubListRouteRouteChildren,
  )

interface protectedProductListRouteRouteChildren {
  protectedProductListSubListRouteRoute: typeof protectedProductListSubListRouteRouteWithChildren
}

const protectedProductListRouteRouteChildren: protectedProductListRouteRouteChildren =
  {
    protectedProductListSubListRouteRoute:
      protectedProductListSubListRouteRouteWithChildren,
  }

const protectedProductListRouteRouteWithChildren =
  protectedProductListRouteRoute._addFileChildren(
    protectedProductListRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedOrderRouteRoute: typeof protectedOrderRouteRouteWithChildren
  protectedPhotoboothRouteRoute: typeof protectedPhotoboothRouteRouteWithChildren
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedUserRoute: typeof protectedUserRoute
  protectedProductListRouteRoute: typeof protectedProductListRouteRouteWithChildren
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedOrderRouteRoute: protectedOrderRouteRouteWithChildren,
  protectedPhotoboothRouteRoute: protectedPhotoboothRouteRouteWithChildren,
  protectedDashboardRoute: protectedDashboardRoute,
  protectedUserRoute: protectedUserRoute,
  protectedProductListRouteRoute: protectedProductListRouteRouteWithChildren,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicDemoComponentRoute: typeof publicDemoComponentRoute
  publicIconRoute: typeof publicIconRoute
  publicLoginRoute: typeof publicLoginRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicDemoComponentRoute: publicDemoComponentRoute,
  publicIconRoute: publicIconRoute,
  publicLoginRoute: publicLoginRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  R401Route: R401Route,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
