export const SIDEBAR_WIDTH = 260
export const SIDEBAR_COLLAPSED_WIDTH = 80

export const TOP_BREADCRUMB_HEIGHT = 64

export const MAIN_CONTAINER_PADDING = 12

export const MAIN_CONTAINER_SCREEN_HEIGHT = `calc(100vh - ${TOP_BREADCRUMB_HEIGHT}px - ${MAIN_CONTAINER_PADDING * 2}px)`
