CREATE TABLE "financial-wallet-history"
(
    id              integer GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_financial_wallet_history"
            PRIMARY KEY,

    "walletId"      integer NOT NULL
        CONSTRAINT "FK_financial_wallet_history_wallet"
            REFERENCES "financial-wallet"(id)
            ON DELETE CASCADE,

    "currentBalance" numeric(10, 2) NOT NULL,
    "newBalance"     numeric(10, 2) NOT NULL,
    "changeAmount"   numeric(10, 2) NOT NULL,

    "createdAt"      timestamp DEFAULT now() NOT NULL
);

ALTER TABLE "financial-wallet-history"
    OWNER TO avnadmin;

CREATE INDEX "IDX_financial_wallet_history_walletId"
    ON "financial-wallet-history" ("walletId");

CREATE INDEX "IDX_financial_wallet_history_createdAt"
    ON "financial-wallet-history" ("createdAt");



CREATE OR REPLACE FUNCTION create_financial_wallet_history()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "financial-wallet-history" (
        "walletId",
        "currentBalance",
        "newBalance",
        "changeAmount"
    )
    VALUES (
        NEW.id,
        OLD.balance,
        NEW.balance,
        NEW.balance - OLD.balance
    );

    RETURN NEW;
END;
$$;

CREATE TRIGGER "TRG_financial_wallet_balance_history"
AFTER UPDATE OF balance
ON "financial-wallet"
FOR EACH ROW
WHEN (OLD.balance IS DISTINCT FROM NEW.balance)
EXECUTE FUNCTION create_financial_wallet_history();