import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  ParseIntPipe,
  Post,
  Query,
  UseInterceptors,
} from "@nestjs/common";
import { ApiBearerAuth, ApiHeader } from "@nestjs/swagger";
import { ApiBaseResponse } from "@/common/decorator/api-swagger/api-base-response.decorator";
import { FinancialTransactionService } from "./financial-transaction.service";
import {
  FinancialTransaction_Create_Request,
  FinancialTransaction_Create_Response,
} from "./dto/create.dto";
import {
  FinancialTransaction_Update_Request,
  FinancialTransaction_Update_Response,
} from "./dto/update.dto";
import { FinancialTransaction_GetAll_Response } from "./dto/get-all.dto";
import {
  FinancialTransaction_Paging_Response,
  type FinancialTransaction_GetAll_Request,
} from "./dto/paging.dto";
import { FinancialTransaction_Delete_Response } from "./dto/delete.dto";
import { FinancialTransactionEntity } from "./_entities/financial-transaction.entity";
import { CreateGenericController } from "@/common/controller/base-crud.controller";
import { CurrentUser } from "@/module/auth/decorator/current-user.decorator";
import type { JwtPayload } from "@/module/auth/payload.type";
import { UseIdempotency } from "@/common/idempotency/idempotency.decorator";
import { IdempotencyInterceptor } from "@/common/idempotency/idempotency.interceptor";

@Controller("financial-transaction")
@ApiBearerAuth("access-token")
/**
 * Idempotency-Key header is required on mutation endpoints.
 * The FE must generate a UUID v4 per user action and send it as:
 *   Idempotency-Key: <uuid-v4>
 */
@ApiHeader({
  name: "Idempotency-Key",
  description:
    "UUID v4 generated by the client. Required for create/update/delete endpoints to ensure idempotency.",
  required: false, // Optional at controller level; enforced per-route by interceptor
})
export class FinancialTransactionController extends CreateGenericController({
  entity: FinancialTransactionEntity,
  dto: {
    create: FinancialTransaction_Create_Request,
    update: FinancialTransaction_Update_Request,
  },
  responses: {
    getAll: FinancialTransaction_GetAll_Response,
    create: FinancialTransaction_Create_Response,
    paging: FinancialTransaction_Paging_Response,
    update: FinancialTransaction_Update_Response,
    delete: FinancialTransaction_Delete_Response,
  },
  excludeSearch: [],
}) {
  constructor(
    private readonly financialTransactionService: FinancialTransactionService,
  ) {
    super(financialTransactionService);
  }

  @Get("/get")
  @HttpCode(200)
  @ApiBaseResponse(FinancialTransaction_GetAll_Response, { isArray: true })
  async get(
    @Query() query: FinancialTransaction_GetAll_Request,
    @CurrentUser() user: JwtPayload,
  ) {
    return this.financialTransactionService.get({ query, user });
  }

  @Get("view/:id")
  @HttpCode(200)
  @ApiBaseResponse(FinancialTransaction_GetAll_Response)
  async view(
    @Param("id", ParseIntPipe) id: number,
    @CurrentUser() user: JwtPayload,
  ) {
    return this.financialTransactionService.view(id, user);
  }

  /**
   * Create a financial transaction.
   *
   * Idempotency-Key REQUIRED. Sending the same key twice will return
   * the cached response without creating a duplicate transaction.
   */
  @Post("/create")
  @HttpCode(201)
  @UseIdempotency()
  @UseInterceptors(IdempotencyInterceptor)
  @ApiBaseResponse(FinancialTransaction_Create_Response)
  @ApiHeader({
    name: "Idempotency-Key",
    description: "UUID v4 — required to prevent duplicate transactions",
    required: true,
  })
  async createOverride(
    @Body() dto: FinancialTransaction_Create_Request,
    @CurrentUser() user: JwtPayload,
  ) {
    return this.financialTransactionService.createOverride(dto, user);
  }

  /**
   * Update a financial transaction.
   *
   * Idempotency-Key REQUIRED for safe retries.
   */
  @Post("/update/:id")
  @HttpCode(200)
  @UseIdempotency()
  @UseInterceptors(IdempotencyInterceptor)
  @ApiBaseResponse(FinancialTransaction_Update_Response)
  @ApiHeader({
    name: "Idempotency-Key",
    description: "UUID v4 — required to prevent duplicate updates",
    required: true,
  })
  async updateOverride(
    @Param("id", ParseIntPipe) id: number,
    @Body() dto: FinancialTransaction_Update_Request,
    @CurrentUser() user: JwtPayload,
  ) {
    return this.financialTransactionService.updateOverride(id, dto, user);
  }

  /**
   * Delete a financial transaction.
   *
   * Idempotency-Key REQUIRED so accidental double-clicks don't result in errors.
   */
  @Delete("/delete/:id")
  @HttpCode(200)
  @UseIdempotency()
  @UseInterceptors(IdempotencyInterceptor)
  @ApiBaseResponse(FinancialTransaction_Delete_Response)
  @ApiHeader({
    name: "Idempotency-Key",
    description: "UUID v4 — required to prevent duplicate deletes",
    required: true,
  })
  async deleteOverride(
    @Param("id", ParseIntPipe) id: number,
    @CurrentUser() user: JwtPayload,
  ) {
    return this.financialTransactionService.deleteOverride(id, user);
  }
}
