export enum FINANCIAL_GOAL_HISTORY_SOURCE {
  USER = "USER",
  SYSTEM = "SYSTEM",
}

export enum FINANCIAL_GOAL_HISTORY_STATUS {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  SKIPPED = "SKIPPED",
}
