export enum FINANCIAL_CATEGORY_TYPE {
  INCOME = "INCOME",
  EXPENSE = "EXPENSE",
  TRANSFER = "TRANSFER",
}

export enum FINANCIAL_CATEGORY_SPENDING_NATURE {
  ESSENTIAL = "ESSENTIAL",
  FLEXIBLE = "FLEXIBLE",
}
